version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: kingstack_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${SUPABASE_DB_URL}
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: kingstack_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    depends_on:
      - backend
    ports:
      - "3000:3000"
