import * as TOML from "@iarna/toml";
import type { ConfigFileMapping, EnvFileConfig } from "./core";

export interface EnvEntry {
  key: string;
  value: string;
}

export function getEnvEntries(
  config: Record<string, string>,
  definition: EnvFileConfig,
): EnvEntry[] {
  const entries: EnvEntry[] = [];

  for (const key of definition.keys) {
    const value = config[key];
    if (value !== undefined) entries.push({ key, value });
  }

  for (const [sourceKey, targetKey] of Object.entries(
    definition.aliases ?? {},
  )) {
    const value = config[sourceKey];
    if (value !== undefined) entries.push({ key: targetKey, value });
  }

  return entries;
}

export function renderEnvFile(
  environment: string,
  config: Record<string, string>,
  definition: EnvFileConfig,
): string {
  const lines = [
    `# Generated from config/${environment}.ts`,
    `# DO NOT EDIT THIS FILE DIRECTLY - edit config/${environment}.ts instead`,
    "",
  ];

  for (const { key, value } of getEnvEntries(config, definition)) {
    lines.push(`${key}=${serializeEnvValue(key, value)}`);
  }

  return `${lines.join("\n")}\n`;
}

export function serializeEnvValue(key: string, value: string): string {
  if (/[\r\n\0]/.test(value)) {
    throw new Error(
      `Configuration value "${key}" cannot contain a newline or NUL`,
    );
  }

  if (/^[A-Za-z0-9_./:@%+,=-]*$/.test(value)) return value;
  return JSON.stringify(value);
}

export function parseEnvFile(content: string): {
  entries: Map<string, string>;
  errors: string[];
} {
  const entries = new Map<string, string>();
  const errors: string[] = [];

  for (const [index, line] of content.split(/\r?\n/).entries()) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const separator = line.indexOf("=");
    if (separator < 1) {
      errors.push(`Line ${index + 1} is not a KEY=value assignment`);
      continue;
    }

    const key = line.slice(0, separator).trim();
    const rawValue = line.slice(separator + 1);
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
      errors.push(`Line ${index + 1} has invalid key "${key}"`);
      continue;
    }
    if (entries.has(key)) {
      errors.push(`Line ${index + 1} repeats key "${key}"`);
      continue;
    }

    try {
      const value = rawValue.startsWith('"')
        ? (JSON.parse(rawValue) as unknown)
        : rawValue;
      if (typeof value !== "string") {
        errors.push(`Line ${index + 1} has a non-string value for "${key}"`);
      } else {
        entries.set(key, value);
      }
    } catch {
      errors.push(`Line ${index + 1} has invalid quoting for "${key}"`);
    }
  }

  return { entries, errors };
}

export function renderTomlFile(
  currentContent: string,
  config: Record<string, string>,
  definition: ConfigFileMapping,
): string {
  const parsed = TOML.parse(currentContent);

  for (const [destination, sourceKey] of Object.entries(definition.mappings)) {
    const value = config[sourceKey];
    if (value === undefined) continue;
    setNestedValue(parsed, destination, coerceTomlValue(destination, value));
  }

  return TOML.stringify(parsed);
}

export function getNestedValue(
  object: Record<string, unknown>,
  path: string,
): unknown {
  let current: unknown = object;
  for (const key of path.split(".")) {
    if (typeof current !== "object" || current === null || !(key in current)) {
      return undefined;
    }
    current = (current as Record<string, unknown>)[key];
  }
  return current;
}

export function coerceTomlValue(path: string, value: string): string | number {
  if (!/(^|[._])port$/i.test(path)) return value;
  const number = Number(value);
  if (!Number.isFinite(number)) {
    throw new Error(
      `TOML mapping "${path}" expected a number, received "${value}"`,
    );
  }
  return number;
}

function setNestedValue(
  object: Record<string, unknown>,
  path: string,
  value: string | number,
): void {
  const keys = path.split(".");
  let current = object;

  for (const key of keys.slice(0, -1)) {
    const existing = current[key];
    if (existing === undefined) {
      const child: Record<string, unknown> = {};
      current[key] = child;
      current = child;
      continue;
    }
    if (
      typeof existing !== "object" ||
      existing === null ||
      Array.isArray(existing)
    ) {
      throw new Error(`Cannot write TOML mapping "${path}" through "${key}"`);
    }
    current = existing as Record<string, unknown>;
  }

  const leaf = keys.at(-1);
  if (!leaf) throw new Error("TOML mapping path cannot be empty");
  current[leaf] = value;
}
