import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join, resolve } from "path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import {
  copyLocalTemplate,
  prepareGeneratedProject,
  replaceNamespace,
  replaceWorkspaceVersions,
} from "../template";

const repoRoot = resolve(process.cwd(), "..", "..");

describe("generated project boundary", () => {
  let testRoot: string;
  let generatedRoot: string;

  beforeAll(() => {
    testRoot = mkdtempSync(join(tmpdir(), "kingstack-template-boundary-"));
    generatedRoot = join(testRoot, "generated");

    expect(copyLocalTemplate(repoRoot, generatedRoot)).toBe(true);
    prepareGeneratedProject(generatedRoot);
    replaceNamespace(generatedRoot, "boundary-check");
    replaceWorkspaceVersions(generatedRoot);
  });

  afterAll(() => {
    rmSync(testRoot, { recursive: true, force: true });
  });

  it("ships only project-owned workspace source", () => {
    expect(readdirSync(join(generatedRoot, "packages")).sort()).toEqual([
      "eslint-config",
      "prisma",
      "shared",
      "ts-config",
    ]);

    for (const excludedPackage of [
      "advanced-optimistic-store",
      "comment-tree",
      "config",
      "create-kingstack",
      "dnd-tree",
      "logger",
    ]) {
      expect(existsSync(join(generatedRoot, "packages", excludedPackage))).toBe(
        false,
      );
    }
  });

  it("uses published KingStack primitive versions", () => {
    const nextPackage = JSON.parse(
      readFileSync(join(generatedRoot, "apps", "next", "package.json"), "utf8"),
    );
    const rootPackage = JSON.parse(
      readFileSync(join(generatedRoot, "package.json"), "utf8"),
    );

    expect(
      nextPackage.dependencies["@kingstack/advanced-optimistic-store"],
    ).toBe("^0.1.0");
    expect(nextPackage.dependencies["@kingstack/comment-tree"]).toBe("^0.2.2");
    expect(nextPackage.dependencies["@kingstack/dnd-tree"]).toBe("^0.2.0");
    expect(nextPackage.dependencies["@kingstack/logger"]).toBe("^0.1.0");
    const nestPackage = JSON.parse(
      readFileSync(join(generatedRoot, "apps", "nest", "package.json"), "utf8"),
    );
    expect(nestPackage.dependencies["@kingstack/logger"]).toBe("^0.1.0");
    expect(rootPackage.devDependencies["@kingstack/config"]).toBe("^0.2.0");

    const nestDockerfile = readFileSync(
      join(generatedRoot, "apps", "nest", "Dockerfile"),
      "utf8",
    );
    expect(nestDockerfile).not.toContain("packages/logger");
    expect(nestDockerfile).not.toContain("workspace @kingstack/logger build");
  });

  it("uses one canonical environment setting", () => {
    const schema = readFileSync(
      join(generatedRoot, "config", "schema.ts"),
      "utf8",
    );
    const example = readFileSync(
      join(generatedRoot, "config", "example.ts"),
      "utf8",
    );

    expect(schema).toContain("environment.mode === EnvironmentMode.Local");
    expect(schema).toContain("KINGSTACK_ENVIRONMENT: environment.environment");
    expect(example).not.toContain("KINGSTACK_ENVIRONMENT:");
    expect(schema).not.toContain("ENVIRONMENT_TYPE");
    expect(example).not.toContain("ENVIRONMENT_TYPE");
  });

  it("excludes maintainer and release infrastructure", () => {
    for (const excludedPath of [
      ".changeset",
      ".github/workflows/release-changeset.yml",
      "docs/archive",
      "scripts/get-public-packages.ts",
      "scripts/test-create-kingstack.ts",
      "setup-guide.md",
      "supabase/.branches",
      "supabase/.temp",
      "template",
      "yarn.lock",
    ]) {
      expect(existsSync(join(generatedRoot, excludedPath))).toBe(false);
    }

    const rootPackage = JSON.parse(
      readFileSync(join(generatedRoot, "package.json"), "utf8"),
    );
    expect(rootPackage.scripts["build:release-packages"]).toBeUndefined();
    expect(rootPackage.scripts["test:create-kingstack"]).toBeUndefined();
    expect(rootPackage.scripts["king-config"]).toBe("bun king-config");
    expect(rootPackage.devDependencies["@changesets/cli"]).toBeUndefined();
  });

  it("installs an application-specific README with valid local links", () => {
    const readme = readFileSync(join(generatedRoot, "readme.md"), "utf8");
    const localLinks = [
      ...readme.matchAll(/\]\((\.\/[^)#]+)(?:#[^)]+)?\)/g),
    ].map((match) => match[1]);

    expect(readme).toContain(
      "This project was generated by `create-kingstack`",
    );
    expect(readme).toContain("KingStack library dependencies");
    expect(readme).not.toContain("Working on KingStack itself");
    expect(localLinks.length).toBeGreaterThan(0);

    for (const link of localLinks) {
      expect(existsSync(resolve(generatedRoot, link))).toBe(true);
    }
  });

  it("carries the repository-wide MIT license into every workspace", () => {
    const manifests = [
      "package.json",
      "apps/nest/package.json",
      "apps/next/package.json",
      "packages/eslint-config/package.json",
      "packages/prisma/package.json",
      "packages/shared/package.json",
      "packages/ts-config/package.json",
    ];

    expect(readFileSync(join(generatedRoot, "LICENSE"), "utf8")).toContain(
      "MIT License",
    );

    for (const manifest of manifests) {
      const packageJson = JSON.parse(
        readFileSync(join(generatedRoot, manifest), "utf8"),
      );
      expect(packageJson.license).toBe("MIT");
    }
  });

  it("keeps only generated-project workflows and runtime scripts", () => {
    expect(
      readdirSync(join(generatedRoot, ".github", "workflows")).sort(),
    ).toEqual([
      "checks-dev.yml",
      "checks-prod.yml",
      "deploy-next-dev.yml",
      "deploy-next-prod.yml",
    ]);
    expect(readdirSync(join(generatedRoot, "scripts")).sort()).toEqual([
      "deploy",
      "enable-backend.ts",
      "project-mode.ts",
      "setup-shadow-db.ts",
      "supabase-check-config.ts",
      "supabase-list-instances.ts",
      "supabase-status.ts",
    ]);
    expect(
      readdirSync(join(generatedRoot, "scripts", "deploy")).sort(),
    ).toEqual(["nest-digitalocean", "nest-digitalocean.ts"]);
    expect(
      readdirSync(
        join(generatedRoot, "scripts", "deploy", "nest-digitalocean"),
      ).sort(),
    ).toEqual([
      "commands.ts",
      "deploy.ts",
      "deployment.test.ts",
      "digitalocean.ts",
      "host-scripts.ts",
      "options.ts",
      "project-config.ts",
      "provision.ts",
      "remote-host.ts",
    ]);

    const rootPackage = JSON.parse(
      readFileSync(join(generatedRoot, "package.json"), "utf8"),
    );
    expect(rootPackage.scripts["deploy:nest"]).toBe(
      "bun scripts/deploy/nest-digitalocean.ts",
    );
    expect(rootPackage.scripts["prisma:deploy"]).toBe(
      "yarn workspace @boundary-check/prisma prisma migrate deploy",
    );
    expect(rootPackage.devDependencies["@types/bun"]).toBeDefined();

    for (const workflow of ["deploy-next-dev.yml", "deploy-next-prod.yml"]) {
      const deployment = readFileSync(
        join(generatedRoot, ".github", "workflows", workflow),
        "utf8",
      );
      expect(deployment).toContain(".kingstack/frontend-draft");
      expect(deployment).toContain("steps.backend.outputs.enabled == 'true'");
      expect(deployment).toContain("run: yarn prisma:deploy");
      expect(deployment).toContain("VERCEL_ORG_ID:");
      expect(deployment).toContain("VERCEL_PROJECT_ID:");
      expect(deployment).toContain("--token $VERCEL_TOKEN");
      expect(deployment).not.toContain("--scope");
      expect(deployment).not.toContain("yarn exec prisma");
    }

    expect(
      readFileSync(join(generatedRoot, "tsconfig.json"), "utf8"),
    ).toContain('"types": ["node", "bun"]');
  });

  it("ships one app-rooted Vercel build configuration", () => {
    expect(existsSync(join(generatedRoot, "vercel.json"))).toBe(false);

    const nextConfig = JSON.parse(
      readFileSync(join(generatedRoot, "apps", "next", "vercel.json"), "utf8"),
    );

    expect(nextConfig.buildCommand).toBe(
      "cd ../.. && yarn turbo run build --filter=@boundary-check/next",
    );
    expect(nextConfig.outputDirectory).toBe(".next");
    expect(nextConfig.ignoreCommand).toBeUndefined();

    const rootPackage = JSON.parse(
      readFileSync(join(generatedRoot, "package.json"), "utf8"),
    );
    expect(rootPackage.scripts.vercel).toBe("vercel deploy");
    expect(rootPackage.scripts["vercel:prod"]).toBe("vercel deploy --prod");
  });
});
