import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Satoshi", "system-ui", "sans-serif"],
        aktura: ["Aktura", "sans-serif"],
        author: ["Author", "sans-serif"],
        anton: ["Anton", "sans-serif"],
        azeret: ["Azeret Mono", "monospace"],
        "bespoke-serif": ["Bespoke Serif", "serif"],
        "bespoke-slab": ["Bespoke Slab", "serif"],
        bevellier: ["Bevellier", "serif"],
        bonny: ["Bonny", "sans-serif"],
        boska: ["Boska", "serif"],
        boxing: ["Boxing", "display"],
        cabinet: ["Cabinet Grotesk", "sans-serif"],
        chillax: ["Chillax", "sans-serif"],
        chubbo: ["Chubbo", "display"],
        clash: ["Clash Display", "sans-serif"],
        crimson: ["Crimson Pro", "serif"],
        epilogue: ["Epilogue", "sans-serif"],
        excon: ["Excon", "sans-serif"],
        expose: ["Expose", "sans-serif"],
        gambarino: ["Gambarino", "serif"],
        gambetta: ["Gambetta", "serif"],
        jetbrains: ["JetBrains Mono", "monospace"],
        literata: ["Literata", "serif"],
        lora: ["Lora", "serif"],
        neco: ["Neco", "sans-serif"],
        "new-title": ["New Title", "serif"],
        nunito: ["Nunito", "sans-serif"],
        oswald: ["Oswald", "sans-serif"],
        pally: ["Pally", "display"],
        paquito: ["Paquito", "sans-serif"],
        "pramukh-rounded": ["Pramukh Rounded", "sans-serif"],
        ranade: ["Ranade", "sans-serif"],
        recia: ["Recia", "serif"],
        roundo: ["Roundo", "sans-serif"],
        rowan: ["Rowan", "serif"],
        satoshi: ["Satoshi", "sans-serif"],
        sentient: ["Sentient", "serif"],
        sora: ["Sora", "sans-serif"],
        supreme: ["Supreme", "sans-serif"],
        switzer: ["Switzer", "sans-serif"],
        synonym: ["Synonym", "sans-serif"],
        tabular: ["Tabular", "sans-serif"],
        zodiak: ["Zodiak", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          border: "hsl(var(--sidebar-border))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        },
        cyan: {
          400: "#22d3ee",
          500: "#06b6d4",
          600: "#0891b2",
        },
        purple: {
          500: "#a855f7",
          600: "#9333ea",
          700: "#7e22ce",
        },
        cream: {
          100: "#FAF9F4",
          200: "#F0EEE6",
          300: "#E2DACB",
        },
        seafoam: {
          100: "#E8F0ED",
          200: "#D1E1DB",
          300: "#BCD0CA",
          DEFAULT: "#BCD0CA",
          400: "#A7C1B8",
          500: "#92B2A6",
          600: "#7DA394",
        },
        lavender: {
          100: "#F0EFF5",
          200: "#E3E2ED",
          DEFAULT: "#CBCADB",
          300: "#CBCADB",
          400: "#B3B1CC",
          500: "#9C99BD",
        },
        lavendar: "#CBCADB",
        mars: {
          DEFAULT: "#D97757",
          300: "#E89A7F",
          400: "#D97757",
          500: "#C86545",
        },
        olive: {
          DEFAULT: "#788C5D",
          300: "#9BAB82",
          400: "#788C5D",
          500: "#647449",
        },
        wheat: {
          200: "#F4EBCE",
          300: "#EFDFAA",
          400: "#EADBBB",
        },
        oceanblue: {
          100: "#B0CBE4",
          DEFAULT: "#6A9BCC",
          200: "#8DB3D8",
          300: "#6A9BCC",
          400: "#5589BD",
          500: "#4177AE",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
