// ============================================================================
// Config generators for create-kingstack CLI
// ============================================================================

import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";
import { DEFAULT_PORTS } from "./constants";
import type { SetupKind } from "./setup";

export const FRONTEND_DRAFT_MARKER = join(".kingstack", "frontend-draft");

// ============================================================================
// Package.json Updates
// ============================================================================

/**
 * Update the root package.json with the new project name
 */
export function updateRootPackageJson(
  targetDir: string,
  projectName: string,
): void {
  const pkgPath = join(targetDir, "package.json");
  const content = readFileSync(pkgPath, "utf-8");
  const pkg = JSON.parse(content);
  pkg.name = projectName;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");
}

// ============================================================================
// Config File Generation
// ============================================================================

/**
 * Generate the config/local.ts file for local development
 */
export function generateLocalConfig(
  targetDir: string,
  projectName: string,
  ports: typeof DEFAULT_PORTS,
): void {
  const configContent = `import { defineValues } from "@kingstack/config";
import type { ConfigValues } from "./schema.js";

/**
 * Local development configuration for ${projectName}
 * Generated by create-kingstack
 */
export const values = defineValues({
    // Application URLs
    NEXT_HOST: "localhost",
    NEST_HOST: "localhost",

    // Application Ports
    NEXT_PORT: "${ports.next}",
    NEST_PORT: "${ports.nest}",
    SUPABASE_DB_SHADOW_PORT: "${ports.supabaseDbShadowPort}",
    SUPABASE_API_PORT: "${ports.supabaseApiPort}",
    SUPABASE_DB_DIRECT_PORT: "${ports.supabaseDbDirectPort}",
    SUPABASE_DB_POOLER_PORT: "${ports.supabaseDbPoolerPort}",
    SUPABASE_STUDIO_PORT: "${ports.supabaseStudioPort}",
    SUPABASE_ANALYTICS_PORT: "${ports.supabaseAnalyticsPort}",
    SUPABASE_EMAIL_PORT: "${ports.supabaseEmailPort}",
    SUPABASE_EDGE_RUNTIME_INSPECTOR_PORT: "${ports.supabaseEdgeRuntimeInspectorPort}",

    // Supabase Configuration (local)
    SUPABASE_PROJECT_REF: "${projectName}-local",
    SUPABASE_REGION: "local",
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",
    SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU",
    SUPA_JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long",
    SUPABASE_DB_PASSWORD: "postgres",

    // Optional: Deployment
    VERCEL_TOKEN: "",
    VERCEL_ORG_ID: "",
    VERCEL_PROJECT_ID: "",

    // Optional: AI Providers
    OPENAI_API_KEY: "",
    ANTHROPIC_API_KEY: "",
    GEMINI_API_KEY: "",

    // Runtime logging. The environment name comes from the CLI argument.
    LOG_LEVEL: "debug",
    LOG_FORMAT: "pretty",

} satisfies ConfigValues);
`;
  writeFileSync(join(targetDir, "config", "local.ts"), configContent, "utf-8");
}

export function configureProjectSetup(
  targetDir: string,
  setup: SetupKind,
): void {
  const markerPath = join(targetDir, FRONTEND_DRAFT_MARKER);

  if (setup === "draft") {
    mkdirSync(join(targetDir, ".kingstack"), { recursive: true });
    writeFileSync(
      markerPath,
      [
        "This marker tells KingStack CI to skip backend database migrations.",
        "Run `yarn backend:enable` to remove it after local backend setup succeeds,",
        "then configure the hosted backend and commit the marker removal.",
        "",
      ].join("\n"),
      "utf-8",
    );
    return;
  }

  rmSync(markerPath, { force: true });
}

// ============================================================================
// Git Initialization
// ============================================================================

/**
 * Initialize a git repository in the target directory
 */
export function initGit(targetDir: string): boolean {
  try {
    execSync("git init", { cwd: targetDir, stdio: "ignore" });
    execSync("git add -A", { cwd: targetDir, stdio: "ignore" });
    execSync('git commit -m "Initial commit from create-kingstack"', {
      cwd: targetDir,
      stdio: "ignore",
    });
    return true;
  } catch {
    return false;
  }
}

// ============================================================================
// Cleanup
// ============================================================================

/**
 * Delete yarn.lock to force fresh dependency resolution
 */
export function deleteYarnLock(targetDir: string): void {
  const lockPath = join(targetDir, "yarn.lock");
  if (existsSync(lockPath)) {
    rmSync(lockPath);
  }
}
