// ============================================================================
// Config generators for create-kingstack CLI
// ============================================================================

import { existsSync, readFileSync, writeFileSync, rmSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";
import { DEFAULT_PORTS } from "./constants";

// ============================================================================
// Package.json Updates
// ============================================================================

/**
 * Update the root package.json with the new project name
 */
export function updateRootPackageJson(targetDir: string, projectName: string): void {
    const pkgPath = join(targetDir, "package.json");
    const content = readFileSync(pkgPath, "utf-8");
    const pkg = JSON.parse(content);
    pkg.name = projectName;
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");
}

// ============================================================================
// Config File Generation
// ============================================================================

/**
 * Generate the config/local.ts file for local development
 */
export function generateLocalConfig(targetDir: string, projectName: string, ports: typeof DEFAULT_PORTS): void {
    const configContent = `import { defineValues } from "@kingstack/config";

/**
 * Local development configuration for ${projectName}
 * Generated by create-kingstack
 */
export const values = defineValues({
    SUPABASE_PROJECT_ID: "${projectName}-local",

    // Application URLs
    NEXT_URL: "localhost",
    NEST_URL: "localhost",

    // Application Ports
    NEXT_PORT: "${ports.next}",
    NEST_PORT: "${ports.nest}",
    SUPABASE_DB_SHADOW_PORT: "${ports.supabaseDbShadowPort}",
    SUPABASE_API_PORT: "${ports.supabaseApiPort}",
    SUPABASE_DB_DIRECT_PORT: "${ports.supabaseDbDirectPort}",
    SUPABASE_DB_POOLER_PORT: "${ports.supabaseDbPoolerPort}",
    SUPABASE_STUDIO_PORT: "${ports.supabaseStudioPort}",
    SUPABASE_ANALYTICS_PORT: "${ports.supabaseAnalyticsPort}",
    SUPABASE_EMAIL_PORT: "${ports.supabaseEmailPort}",

    // Supabase Configuration (local)
    SUPABASE_PROJECT_REF: "${projectName}-local",
    SUPABASE_REGION: "local",
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",
    SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU",
    SUPA_JWT_SECRET: "super-secret-jwt-token-with-at-least-32-characters-long",
    SUPABASE_DB_PASSWORD: "postgres",

    // Optional: OAuth
    GOOGLE_CLIENT_ID: "",
    GOOGLE_CLIENT_SECRET: "",

    // Optional: Deployment (placeholders for local - schema requires non-empty)
    VERCEL_TOKEN: "local-not-configured",
    VERCEL_ORG_ID: "local-not-configured",
    VERCEL_PROJECT_ID: "local-not-configured",

    // Optional: AI Providers
    OPENAI_API_KEY: "",
    ANTHROPIC_API_KEY: "",
    GEMINI_API_KEY: "",

    // Stripe
    STRIPE_PUBLIC_KEY: "",
    STRIPE_SECRET_KEY: "",
    STRIPE_WEBHOOK_SECRET: "",

    // Resend (Email)
    RESEND_API_KEY: "",

    // Ecommerce
    NEXT_PUBLIC_INVENTORY_POOL_ID: "",

    // Environment Type
    ENVIRONMENT_TYPE: "local",
});
`;
    writeFileSync(join(targetDir, "config", "local.ts"), configContent, "utf-8");
}

/**
 * Generate/update the config/playground.ts file with valid placeholder values
 */
export function updatePlaygroundConfig(targetDir: string, projectName: string): void {
    const playgroundConfigContent = `import { defineValues } from "@kingstack/config";

/**
 * Playground mode values - safe mock data for development without a backend.
 * Generated by create-kingstack for ${projectName}
 * 
 * This file can be checked into version control since it contains no real secrets.
 */
export const values = defineValues({
    // ============================================================================
    // Application Configuration
    // ============================================================================
    NEXT_HOST: "localhost",
    NEST_HOST: "localhost",
    NEXT_PORT: "3069",
    NEST_PORT: "3000",

    // ============================================================================
    // Supabase Configuration (Playground placeholders)
    // ============================================================================
    SUPABASE_PROJECT_REF: "${projectName}-playground",
    SUPABASE_REGION: "local",
    SUPABASE_API_URL: "https://playground.supabase.co",
    SUPABASE_ANON_KEY: "mock-anon-key-for-playground",
    SUPABASE_SERVICE_ROLE_KEY: "mock-service-role-key-for-playground",
    SUPA_JWT_SECRET: "mock-jwt-secret-for-playground-environment",
    SUPABASE_DB_PASSWORD: "playground",

    // ============================================================================
    // Database Configuration (Mock)
    // ============================================================================
    SUPABASE_POOLER_HOST: "localhost",
    SUPABASE_POOLER_USER: "postgres.playground",

    // ============================================================================
    // Optional: OAuth (Empty for playground)
    // ============================================================================
    GOOGLE_CLIENT_ID: "",
    GOOGLE_CLIENT_SECRET: "",

    // ============================================================================
    // Deployment (Placeholders for playground)
    // ============================================================================
    VERCEL_TOKEN: "playground-not-configured",
    VERCEL_ORG_ID: "playground-not-configured",
    VERCEL_PROJECT_ID: "playground-not-configured",

    // ============================================================================
    // Optional: AI Providers (Empty for playground)
    // ============================================================================
    OPENAI_API_KEY: "",
    ANTHROPIC_API_KEY: "",
    GEMINI_API_KEY: "",

    // Environment Type
    ENVIRONMENT_TYPE: "local",
});
`;
    writeFileSync(join(targetDir, "config", "playground.ts"), playgroundConfigContent, "utf-8");
}

// ============================================================================
// Git Initialization
// ============================================================================

/**
 * Initialize a git repository in the target directory
 */
export function initGit(targetDir: string): boolean {
    try {
        execSync("git init", { cwd: targetDir, stdio: "ignore" });
        execSync("git add -A", { cwd: targetDir, stdio: "ignore" });
        execSync('git commit -m "Initial commit from create-kingstack"', {
            cwd: targetDir,
            stdio: "ignore",
        });
        return true;
    } catch {
        return false;
    }
}

// ============================================================================
// Cleanup
// ============================================================================

/**
 * Delete yarn.lock to force fresh dependency resolution
 */
export function deleteYarnLock(targetDir: string): void {
    const lockPath = join(targetDir, "yarn.lock");
    if (existsSync(lockPath)) {
        rmSync(lockPath);
    }
}
